apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: kuard
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: kuard
        version: "2"
    spec:
      containers:
        - name: helloworld
          image: kelseyhightower/helloworld:v1
          ports:
            - containerPort: 80
